version: "2"
run:
  concurrency: 8
  tests: false
linters:
  enable:
    - gochecknoinits
    - goconst
    - revive
    - rowserrcheck
    - staticcheck
    - unparam
  exclusions:
    generated: lax
    paths:
      - docs/docs.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/sendlovebox
  exclusions:
    generated: lax
    paths:
      - docs/docs.go
      - third_party$
      - builtin$
      - examples$
